2021-05-12 14:33:38,489 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NSwiZXhwIjoxNjIwODQ1MDA4LjMwMTM3ODV9.39ReLipDjLkRq_RVw_htMLlmAub_WVagB5ykpV16g1E [GET] [in /home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/szwhite/shayblog/myapp/routes.py", line 115, in reset_password
    return render_template('reset_password.html', form=form)
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/szwhite/shayblog/myapp/templates/reset_password.html", line 10, in template
    {{% for error in form.password.errors %}}
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
2021-05-12 14:35:13,536 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:45]
2021-05-13 14:26:17,349 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:47]
2021-05-13 14:35:03,274 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:47]
2021-05-13 14:36:24,465 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:47]
2021-05-13 14:44:12,415 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:47]
2021-05-13 15:31:38,172 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:49]
2021-05-14 14:23:11,763 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-14 14:25:32,195 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 09:44:09,804 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 11:19:44,095 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 11:39:46,025 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 11:42:52,281 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 12:23:03,650 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 12:23:12,817 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 12:25:11,242 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 12:26:03,454 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 12:26:10,256 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 12:26:14,630 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 12:27:02,674 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 12:37:29,300 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 12:37:40,340 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 12:38:08,747 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 12:42:04,788 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 13:30:39,621 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-17 13:30:45,163 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:52]
2021-05-18 11:16:28,604 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-18 11:54:34,199 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-18 13:19:21,010 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-18 13:19:32,331 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-18 13:20:17,154 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-18 13:29:31,353 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-18 13:31:16,063 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-18 13:38:54,152 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-18 13:50:53,297 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-19 08:19:37,142 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-19 08:29:10,169 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-19 08:43:48,032 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-19 10:05:06,352 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-19 10:05:14,061 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-19 10:05:22,334 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-19 10:09:55,005 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-19 10:10:00,578 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-19 10:14:01,725 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-19 10:21:14,339 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-19 16:08:46,277 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:53]
2021-05-19 18:01:11,886 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:70]
2021-05-19 18:01:20,304 ERROR: Exception on /explore [GET] [in /home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/home/szwhite/shayblog/myapp/main/routes.py", line 18, in before_request
    g.locale = str(get_locale())
  File "/home/szwhite/shayblog/sbvenv/lib/python3.8/site-packages/flask_babel/__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "/home/szwhite/shayblog/myapp/__init__.py", line 77, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'app' is not defined
2021-05-19 18:02:16,856 INFO: ShayBlog startup [in /home/szwhite/shayblog/myapp/__init__.py:70]
